import turtle
turtle.color("red")
turtle.right(90)
turtle.forward(30)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(80)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(30)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(15)

turtle.left(90)
turtle.forward(20)
turtle.backward(20)
turtle.right(90)

turtle.forward(25)

turtle.left(90)
turtle.forward(20)
turtle.backward(20)
turtle.right(90)

turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(50)
turtle.right(90)

turtle.left(90)
turtle.forward(20)
turtle.backward(20)
turtle.right(90)

turtle.forward(15)
turtle.left(45)
turtle.forward(21)
turtle.color("white")
turtle.right(45)
turtle.forward(30)
turtle.exitonclick()
